# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    # Group updates for eslint packages into a single PR
    groups:
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"

